### ISSUE TITLE
No movies showing up for year 2010 and up

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_532_group_205_movies_R#7]
As Alejandra brought up in #5, if you select a starting year of 2010 (ending year 2011), there seems to be no movies.

@sreejithmunthikodu Can you check why this is the case while you are working on the lower scatterplot? Thanks.

**Comment by fkhan72** [comment]
This issue was due to data wrangling in the Python version of the app. I have tested the R version and it works fine.

**Comment by techrah** [comment]
Fixed in #12
