### ISSUE TITLE
Reflections

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_532_group_205_movies_R#8]
I'm starting a thread here to add reflections as we come across issues that we are not able to solve... or anything else you feel should be added.

### Currently unable to hide graph controls.

The following code does not work when embedded in a DashR app:

```
gp = ggplotly(p)
gp %>% config(displayModeBar = FALSE)
```

This is apparently a known issue with the more recent versions of plotly.

**Comment by fkhan72** [comment]
I have included this in the reflections

**Comment by techrah** [comment]
### Issues with labelling points with a bubble + line

See #6 for details.

However, we did get chart-to-chart interactivity to work so this may provide enough of a workaround.

**Comment by techrah** [comment]
### Hide charts and display user message when no data to show

Tried to do this and was making progress but the technique that I was using, which dynamically created the `dccGraph` chart objects affected the ability to implement the chart-to-chart interactivity so I reverted my changes and aborted this feature.

**Comment by techrah** [comment]
### Chart-to-chart interactivity limitations
- When the chart is first displayed, all bars are selected; no option to start with all bars faded which will clue the user to select one.
- Once a bar has been selected, the user can select that same bar to reset the chart to all bars selected. However, there is no way to communicate this to the other chart. The event triggered is the same as when a single bar is being selected.

**Comment by techrah** [comment]
### App deployed to Heroku is much slower than anticipated

Delay after interaction before charts get updated

**Comment by sreejithmunthikodu** [comment]
Updated reflection.md
#17
