### ISSUE TITLE
Chart 1 (upper barchart) Visual Updates

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_532_group_205_movies_R#9]
The tooltips need to be formatted. The following items should be shown:

- Year
- Genre
- MPAA Rating
- Gross Revenue (millions)

Also, instead of that brown colour, can we use the same green as the top banner? This would give more cohesiveness to the app. The hex colour is #396362.

<img width="975" alt="r_v1_highest_grossing" src="https://user-images.githubusercontent.com/600471/70843097-86860a80-1de1-11ea-99cd-9d8fa5a64eb3.png">

**Comment by techrah** [comment]
@fkhan72 I know we discussed this but it has been handled in #11.

<img width="992" alt="r_v2_highest_grossing" src="https://user-images.githubusercontent.com/600471/70844780-a70e8e80-1dfa-11ea-92cb-966d8d249945.png">

Is there any more data that we'd like to add to the tooltip?

**Comment by fkhan72** [comment]
Looks good. I also finished doing these changes on my local repo. What should I do now?
